version: '2'
services:
  pdfreactor:
    extends:
      file: src/docker/pdfreactor.yml
      service: pdfreactor
  electronpdf:
    extends:
      file: src/docker/electronpdf.yml
      service: electronpdf
  pdfizer:
    build: .
    links:
    - electronpdf
    - pdfreactor
    ports:
     - 8080:8080
    env_file:
    - src/docker/.env
